#! /bin/sh
# $Id: nuke-stale-cvs-data,v 1.2 1997/03/31 18:24:46 friedman Exp $

# Looks for /tmp/cvs-serv* data left from CVS server processes which exited
# without reaping those temporary files.  This script works on Solaris 2,
# Irix 5, and Irix 6.  Your mileage may vary on other systems.

case "$1" in
  -f ) force=t; shift;;
  *  ) force=nil ;;
esac

case "$1" in
  -q ) quick=t ; shift;;
  *  ) force=nil ;;
esac


PATH="/bin:$PATH"

prefix=/tmp/cvs-serv

for pid in `ls -1d ${prefix}* 2> /dev/null | sed "s=$prefix=="`; do
  dir="$prefix$pid"

  if ps -p $pid > /dev/null; then
    continue
  fi

  test -d "$dir" || continue

  echo "Stale CVS data directory: \c"
  {
    if test "$quick" = "t" ; then
      echo "?? \c"
    else
      blocks=`du -sk "$dir" | sed 's/[^0-9].*//'`
      echo "$blocks \c"
    fi
    ls -l1d "$dir"
  } | awk '{ print  $4, $1 "k", $7, $8, $9, $10 }'

  case "$force" in
    t ) rm -rf "$prefix$pid" ;;
    * )
      echo "Delete recursively (y/n)? \c"
      read ans

      case "$ans" in
        y* | Y* )
          echo rm -rf "$prefix$pid"
          rm -rf "$prefix$pid"
         ;;
      esac
      echo
     ;;
  esac
done

# eof
