#!/bin/sh

uv_export()
{
    local repo=$1
    shift

    local uvdir=${repo##*/}
    local uvdir=${uvdir%.fossil}.uv
    local dst=$uvdir/export

    mkdir -p $dst

    fossil uv ls -l -R $repo |
        while read cksum date time size1 size2 file; do
            echo $file
            fossil uv export -R $repo $file $dst/$file
            touch -d "$date $time" $dst/$file
        done
}

main()
{
    for repo in "$@"; do
        uv_export "$repo"
    done
}

main "$@"

# eof
