#!/bin/sh
# $Id: git-revstamp,v 1.1 2018/03/08 03:13:52 friedman Exp $

cd "${1-.}" || exit $?

${GITPROG-git} log -n 1 --format="tformat:%h %ci" "${2-@}" |
    while read hash tmstr; do
        date -u -d "$tmstr" +"%Y-%m-%d--%H-%M-%S--$hash"
    done
