#!/bin/sh
# $Id: git-mclone,v 1.4 2017/12/20 20:15:18 friedman Exp $

case $1 in
    --bare   ) mode=$1 ; shift  ;;
    --mirror ) mode=$1 ; shift  ;;
    *        ) mode=--recursive ;;
esac

for url in "$@"; do
    localdir=${url##*/}
    localdir=${localdir%.git}.git  # make sure it ends in .git

    echo "** $url"
    git clone $mode "$url" "$localdir" || continue

    case $mode in
        --bare | --mirror )
            tm=`git -C "$localdir" log -n1 --format=tformat:%ci`
            find "$localdir" -exec touch -d "$tm" '{}' + ;;
        * )
            (cd "$localdir" && git-restore-commit-mtime) ;;
    esac
    echo
done

# eof
