#!/bin/sh
# Display upstream urls in git repositories

for repo in "$@"; do
    echo -n "${repo##*/}" ""
    git -C "$repo" config --local --get-regexp '^remote\..*\.url$' || echo $?
done |
    sed 's= remote\.\([^ ]*\)\.url = \1 =' |
    column -t -s'  '

# eof
