#!/bin/sh
# $Id: git-update,v 1.1 2015/10/31 07:22:05 friedman Exp $

git_revno()
{
    git rev-list -n1 HEAD
}

main()
{
    cd "${1-.}" || exit $?

    revno_old=`git_revno`
    git pull --rebase=preserve --no-stat --all
    revno_new=`git_revno`

    git-restore-commit-mtime $revno_old..$revno_new
}

main "$@"

# eof
