#!/bin/sh
# Display upstream urls in git repositories

for repo in "$@"; do
    echo -n "${repo##*/}" ""
    git -C "$repo" config --local --get-regexp '^remote\..*\.url$' || echo $?
done |
    sed 's= remote\.\([^ ]*\)\.url = \1 =' |
    if [ -t 1 ]; then
        # only fold at long columns if stdout is to a tty
        column -t -s'  ' -E1
    else
        column -t -s'  '
    fi

# eof
