#!/usr/bin/env bash
# git "shared" but disconnected clone, useful for local throwaway repositories.
# Author: Noah Friedman <friedman@splode.com>
# Created: 2019-08-18
# Public domain

# $Id$

# Commentary:

# Removes upstream information to avoid accidental contamination of
# original while still making history available.

# Code:

: ${GITPROG:=git}

main()
{
    arg=( "$@" )
    dstdir=${arg[-1]}
    unset arg[-1]

    if [[ -d $dstdir ]]; then
        srcdir=$dstdir
        dstdir=${srcdir##*/}
        dstdir=${dstdir%.git}
    else
        srcdir=${arg[-1]}
        unset arg[-1]
    fi

    emptydir=${XDG_RUNTIME_DIR-${TMPDIR-/tmp}}/empty.$$
    trap 'rmdir "$emptydir"' 0 1 2 3 15
    (umask 077; mkdir -p "$emptydir")

    $GITPROG clone --shared --template "$emptydir" "${arg[@]}" -- "$srcdir" "$dstdir"
    $GITPROG -C "$dstdir" branch --unset-upstream
    $GITPROG -C "$dstdir" config --unset remote.origin.url
    $GITPROG -C "$dstdir" restore-commit-mtime
}

main "$@"

# eof
