#!/bin/sh
# Display upstream urls in git repositories
# n.b. similar to `git remote -v' but no separate lines for fetch/push
# and display local repo directory name.

if [ $# -eq 0 ]; then set . ; fi

for repo in "$@"; do
    echo -n "${repo##*/}" ""
    git -C "$repo" config --local --get-regexp '^remote\..*\.url$' || echo $?
done |
    sed 's= remote\.\([^ ]*\)\.url = \1 =' |
    column -t -s'  '

# eof
