#!/bin/sh
# $Id: git-update,v 1.2 2015/11/20 23:02:07 friedman Exp $

git_revno()
{
    git rev-list -n1 HEAD
}

main()
{
    cd "${1-.}" || exit $?
    case $2 in
        --rebase ) rebase=--rebase=preserve ;;
    esac

    revno_old=`git_revno`
    git pull $rebase --no-stat --all
    revno_new=`git_revno`

    git-restore-commit-mtime $revno_old..$revno_new
}

main "$@"

# eof
