#!/bin/sh
# $Id$
# Public domain

revlist()
{
    p4 -F %depotRev% filelog "$@" | tac
}

p4diff2()
{
    p4 diff2 ${P4_DIFF_FLAGS- -dbu} "$3$1" "$3$2"
}

main()
{
    for file in "$@"; do
        set x `revlist $file`
        shift
        while [ $# -gt 1 ]; do
            p4diff2 $1 $2 "$file"
            shift
        done
    done
}

main "$@"

# eof
