#!/bin/sh

for repo in "$@"; do
    if [ -f "$repo/.svn/wc.db" ]; then
        sqlite3 -noheader -batch "$repo/.svn/wc.db" "select root from repository"
    else
        # This relies on a private prop used by svn-mirror
        svnlook propget --revprop -r0 "$repo" svn:sync-from-url
        echo
    fi
done
